
// Hybrid allocator using DRAM (jemalloc) up to a limit, then PMEM (UMF)
use core::alloc::{GlobalAlloc, Layout};
use std::sync::{Once, atomic::{AtomicUsize, Ordering}};
use std::ptr;
use tikv_jemallocator::Jemalloc;
use std::ptr::NonNull;

//#[cfg(feature = "allocator_api")]
use std::alloc::{Allocator, AllocError};


mod allocator_bindings {
    include!("umf_allocator_bindings.rs"); // generated by bindgen
}

/// Hybrid allocator: first DRAM up to a limit, then PMEM
pub struct HybridGlobal;

static INIT: Once = Once::new();
static DRAM_ALLOCATED: AtomicUsize = AtomicUsize::new(0);

//with 100gb local and setting object custom allocator to use only pmem... u get pmem performance of having objects only in pmem....
static mut DRAM_LIMIT: usize = 0; // default 100 GiB

static PRINT_THRESHOLD: usize = 10000;
static mut NUM_ALLOCS: usize = 0;
static mut NUM_DEALLOCS: usize = 0;
static ALL_MEM_ALLOCATED: AtomicUsize = AtomicUsize::new(0);


//#[cfg(feature = "allocator_api")]
unsafe impl GlobalAlloc for HybridGlobal {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {

        if DRAM_LIMIT == 0 {
            unsafe {
                INIT.call_once(|| {
                    let dax_size = 118377938944; // PMEM size from ndctl list --namespaces
                    let dax_path = b"/dev/dax0.1\0".as_ptr() as *const i8; // PMEM path from ndctl list --namespaces
                    allocator_bindings::umf_allocator_init(
                        dax_path,
                        dax_size,
                        );
                #[cfg(debug_assertions)] {println!("Initialized PMEM allocator with DAX path /dev/dax0.0 and size {}", dax_size);}
                });
            }
            // Default DRAM limit of 100 GiB
            let ptr = allocator_bindings::umf_alloc(layout.size(), layout.align()) as *mut u8;
            if ptr.is_null() { eprintln!("Failed to allocate PMEM"); return ptr::null_mut(); }

            //println!("SERVER: allocated size (align): {}", layout.align());
            //println!("SERVER: allocated size (size): {}", layout.size());
            //println!("SERVER: allocated ptr: {:p}", ptr);

            return ptr;
        }

        if DRAM_LIMIT == 1000 * 1024 * 1024 * 1024 {
            let ptr = Jemalloc.alloc(layout);
            if ptr.is_null() { eprintln!("Failed to allocate DRAM"); return ptr::null_mut(); }
            return ptr;
        }


        // Decide backend
        let raw = if Self::should_use_dram(layout.size()) {
            let ptr = Jemalloc.alloc(layout);
            if ptr.is_null() { eprintln!("Failed to allocate DRAM"); return ptr::null_mut(); }
            DRAM_ALLOCATED.fetch_add(layout.size(), Ordering::SeqCst);
            #[cfg(debug_assertions)] {ALL_MEM_ALLOCATED.fetch_add(layout.size(), Ordering::SeqCst);}
            ptr
        } else {
            unsafe {
                INIT.call_once(|| {
                    let dax_size = 118377938944; // PMEM size from ndctl list --namespaces
                    let dax_path = b"/dev/dax0.1\0".as_ptr() as *const i8; // PMEM path from ndctl list --namespaces
                    allocator_bindings::umf_allocator_init(
                        dax_path,
                        dax_size,
                        );
                });
            }
            let ptr = allocator_bindings::umf_alloc(layout.size(), layout.align()) as *mut u8;
            if ptr.is_null() { eprintln!("Failed to allocate PMEM"); return ptr::null_mut(); }
            #[cfg(debug_assertions)] {ALL_MEM_ALLOCATED.fetch_add(layout.size(), Ordering::SeqCst);}
            ptr
        };

        //for debug only.....
       
        #[cfg(debug_assertions)] {
            unsafe {

                if PRINT_THRESHOLD < NUM_ALLOCS {
                    let total_alloc = ALL_MEM_ALLOCATED.load(Ordering::SeqCst);
                    let dram_alloc = DRAM_ALLOCATED.load(Ordering::SeqCst);
                    println!("Allocated: total {} bytes, DRAM {} bytes ({:.2}%), PMEM {} bytes ({:.2}%)",
                        total_alloc,
                        dram_alloc,
                        dram_alloc as f64 / total_alloc as f64 * 100.0,
                        total_alloc - dram_alloc,
                        (total_alloc - dram_alloc) as f64 / total_alloc as f64 * 100.0,
                    );
                    println!("alloc requested layout size: {}", layout.size());
                    println!("alloc layout align size: {}", layout.align());
                    println!("raw pointer {:p}", raw);
                    NUM_ALLOCS = 0;
                }
                NUM_ALLOCS += 1;

            }
        }
        raw
    }

    unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
        
        
        if DRAM_LIMIT == 0 {
            unsafe { allocator_bindings::umf_dealloc(ptr as *mut std::ffi::c_void); }
            //ALL_MEM_ALLOCATED.fetch_sub(layout.size(), Ordering::SeqCst);
            //println!("deallocated ptr: {:p}", ptr);
            //println!("deallocated size (align): {}", layout.align());
            //println!("deallocated size (size): {}", layout.size());
            return;
        }
        if DRAM_LIMIT == 1000 * 1024 * 1024 * 1024 {
            unsafe { Jemalloc.dealloc(ptr as *mut u8, layout); }
            return;
        }
                


        // Check the tier of the allocated memory only if not all in pmem or all in dram
        let tier = unsafe {allocator_bindings::check_tier(ptr as *mut std::ffi::c_void)};

        if tier == 0 {
            // DRAM
            unsafe { Jemalloc.dealloc(ptr as *mut u8, layout); }
            //DRAM_ALLOCATED.fetch_sub(layout.size(), Ordering::SeqCst);
            //ALL_MEM_ALLOCATED.fetch_sub(layout.size(), Ordering::SeqCst);
        } else {
            //pmem
            unsafe { allocator_bindings::umf_dealloc(ptr as *mut std::ffi::c_void); }
            //ALL_MEM_ALLOCATED.fetch_sub(layout.size(), Ordering::SeqCst);
        }

        #[cfg(debug_assertions)] { 
            unsafe {

                if PRINT_THRESHOLD < NUM_DEALLOCS {
                    let total_alloc = ALL_MEM_ALLOCATED.load(Ordering::SeqCst);
                    let dram_alloc = DRAM_ALLOCATED.load(Ordering::SeqCst);
                    println!("Allocated: total {} bytes, DRAM {} bytes ({:.2}%), PMEM {} bytes ({:.2}%)",
                        total_alloc,
                        dram_alloc,
                        dram_alloc as f64 / total_alloc as f64 * 100.0,
                        total_alloc - dram_alloc,
                        (total_alloc - dram_alloc) as f64 / total_alloc as f64 * 100.0,
                    );
                    NUM_DEALLOCS = 0;
                    println!("dealloc requested layout size: {}", layout.size());
                    println!("dealloc layout align size: {}", layout.align());
                    println!("raw pointer {:p}", ptr);
                    println!("tier 0 is dram, 1 is pmem: {}", tier);
                }
                NUM_DEALLOCS += 1;
            }
        }
    }
}

//#[cfg(feature = "allocator_api")]
impl HybridGlobal {
    /// Set the DRAM limit in bytes
    pub fn set_dram_limit(limit: usize) {
        unsafe { DRAM_LIMIT = limit; }
        println!("Set DRAM limit to {} bytes", limit);
    }

    /// Determine whether to allocate from DRAM
    fn should_use_dram(size: usize) -> bool {
        let current = DRAM_ALLOCATED.load(Ordering::SeqCst); //this was relaxed... but i made it seqcst which might limit performance
        unsafe { current + size <= DRAM_LIMIT }
    }
}



//#[cfg(feature = "allocator_api")]
unsafe impl Allocator for HybridGlobal {
    fn allocate(&self, layout: Layout) -> Result<NonNull<[u8]>, AllocError> {
        unsafe {
            HybridGlobal::alloc(self, layout)
                .as_mut()
                .map(|ptr| NonNull::slice_from_raw_parts(NonNull::new_unchecked(ptr), layout.size()))
                .ok_or(AllocError)
        }
    }

    unsafe fn deallocate(&self, ptr: NonNull<u8>, layout: Layout) {
        HybridGlobal::dealloc(self, ptr.as_ptr(), layout);
    }
}

 


